editAreaLoader.lang["ch"]={
new_document: "新建文件",
search_button: "查找替换",
search_command: "查找下一个",
search: "查找(Ctrl+f)",
search2: "查找",
replace: "替换",
replace_command: "替换",
find_next: "查找下一个",
replace_all: "替换所有",
reg_exp: "正则表达式",
match_case: "区分大小写",
not_found: "没有找到.",
occurrence_replaced: "替换完成.",
search_field_empty: "查找字符串不能为空",
restart_search_at_begin: "已到尾部,从头部重新查找.",
move_popup: "移动窗口",
font_size: "--文字大小--",
go_to_line: "跳转到行(Ctrl+g)",
go_to_line_prompt: "跳转到行:",
undo: "撤销(Ctrl+z)",
redo: "重做(Ctrl+y)",
change_smooth_selection: "打开/关闭 显示特效",
highlight: "打开/关闭 语法高亮",
reset_highlight: "重置语法高亮",
help: "关于",
save: "保存(Ctrl+s)",
load: "载入",
line_abbr: "行",
char_abbr: "字符",
position: "位置",
total: "共有",
close_popup: "关闭窗口",
shortcuts: "快捷方式",
add_tab: "插入制表符",
remove_tab: "移除制表符",
about_notice: "注意: 语法高亮仅对少量文本有效",
toggle: "切换模式",
accesskey: "快捷键",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "处理中...",
fullscreen: "全屏",
syntax_selection: "--语言--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "关闭文件"
};
