editAreaLoader.lang["ko"]={
new_document: "새 빈 문서",
search_button: "검색 & 대체",
search_command: "텍스트 검색 / 검색 영역 열기",
search: "검색(Ctrl+f)",
search2: "검색",
replace: "대체",
replace_command: "대체 / 검색 영역 열기",
find_next: "다음 찾기",
replace_all: "모두 대체",
reg_exp: "정규식 표현",
match_case: "대소문자 구분",
not_found: "찾을 수 없습니다.",
occurrence_replaced: "대체가 발생했습니다.",
search_field_empty: "검색란이 비었습니다.",
restart_search_at_begin: "영역의 끝에서 다시 시작",
move_popup: "검색 팝업 이동",
font_size: "--글꼴 크기--",
go_to_line: "줄 찾아가기(Ctrl+g)",
go_to_line_prompt: "줄 번호 찾아가기:",
undo: "실행 취소(Ctrl+z)",
redo: "다시 실행(Ctrl+y)",
change_smooth_selection: "어떤 표시 기능 활성화/비활성화 (더 빠르게 표시되지만 CPU를 더 사용함)",
highlight: "구문 강조 ON/OFF 전환",
reset_highlight: "강조 재설정 (텍스트로부터 동기화된 경우)",
help: "정보",
save: "저장(Ctrl+s)",
load: "불러오기",
line_abbr: "Ln",
char_abbr: "Ch",
position: "위치",
total: "전체",
close_popup: "팝업 닫기",
shortcuts: "단축키",
add_tab: "텍스트에 표 추가",
remove_tab: "텍스트에서 표 제거",
about_notice: "알림: 구문 강조 기능은 작은 텍스트 전용입니다.",
toggle: "토글 편집기",
accesskey: "엑세스 키",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "처리 중...",
fullscreen: "전체 화면",
syntax_selection: "--Syntax--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "파일 닫기"
};
