editAreaLoader.lang["big5"]={
new_document: "新建文件",
search_button: "查找替換",
search_command: "查找下一個",
search: "查找(Ctrl+f)",
search2: "查找",
replace: "替換",
replace_command: "替換",
find_next: "查找下一個",
replace_all: "替換所有",
reg_exp: "正則表達式",
match_case: "區分大小寫",
not_found: "沒有找到.",
occurrence_replaced: "替換完成.",
search_field_empty: "查找字符串不能為空",
restart_search_at_begin: "已到尾部,從頭部重新查找.",
move_popup: "移動窗口",
font_size: "--文字大小--",
go_to_line: "跳轉到行(Ctrl+g)",
go_to_line_prompt: "跳轉到行:",
undo: "撤銷(Ctrl+z)",
redo: "重做(Ctrl+y)",
change_smooth_selection: "打開/關閉 顯示特效",
highlight: "打開/關閉 語法高亮",
reset_highlight: "重置語法高亮",
help: "關于",
save: "保存(Ctrl+s)",
load: "載入",
line_abbr: "行",
char_abbr: "字符",
position: "位置",
total: "共有",
close_popup: "關閉窗口",
shortcuts: "快捷方式",
add_tab: "插入制表符",
remove_tab: "移除制表符",
about_notice: "注意: 語法高亮僅對少量文本有效",
toggle: "切換糢式",
accesskey: "快捷鍵",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "處理中...",
fullscreen: "全屏",
syntax_selection: "--語言--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "關閉文件"
};
