editAreaLoader.lang["ro"]={
new_document: "document nou gol",
search_button: "caută și înlocuiește",
search_command: "caută următoarea / deschide zona de căutare",
search: "caută(Ctrl+f)",
search2: "caută",
replace: "înlocuiește",
replace_command: "înlocuiește / deschide zona de căutare",
find_next: "găsește următorul",
replace_all: "înlocuiește tot",
reg_exp: "expresii regulare",
match_case: "caz egal",
not_found: "nu a fost găsit.",
occurrence_replaced: "aparițiile au fost înlocuite.",
search_field_empty: "Câmp pentru căutare gol",
restart_search_at_begin: "Limita zonei a fost atinsă. Repornește la început.",
move_popup: "mută popup-ul de căutare",
font_size: "--Dimensiunea font-ului--",
go_to_line: "mergi la linia(Ctrl+g)",
go_to_line_prompt: "du-te la linia numărul:",

undo: "undo(Ctrl+z)",
redo: "redo(Ctrl+y)",
change_smooth_selection: "activează/dezactivează opțiuni de display (display-ul inteligent folosește mai multe resurse)",
highlight: "declanșează sublinierea sintaxei on/off",
reset_highlight: "resetează sublinierea (dacă a fost desincronizată din text)",
help: "despre",
save: "salvează(Ctrl+s)",
load: "încarcă",

line_abbr: "Ln",
char_abbr: "Ch",
position: "Poziție",
total: "Total",
close_popup: "închide popup",
shortcuts: "Shortcuts",
add_tab: "adaugă centralizare la text",
remove_tab: "elimină centralizarea din text",
about_notice: "Aviz: funcția de subliniere a sintaxei este doar pentru textul de mărime mică",
toggle: "Editor de declanșare",
accesskey: "Cheia de acces",

tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Se procesează...",
fullscreen: "ecran mare",
syntax_selection: "--Sintaxă--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "Închide fișierul"
};