editAreaLoader.lang["tr"]={
new_document: "Yeni boş belge",
search_button: "Bul ve Değiştir",
search_command: "Sonrakini ara / Arama alanını aç",
search: "Ara(Ctrl+f)",
search2: "Ara",
replace: "Değiştir",
replace_command: "Değiştir / Arama alanını aç",
find_next: "Sonrakini bul",
replace_all: "Tümünü değiştir",
reg_exp: "Düzenli ifadeler",
match_case: "Büyük küçük harfe duyarlı",
not_found: "bulunamadı.",
occurrence_replaced: "olaylar değiştirildi.",
search_field_empty: "Arama alanı boş",
restart_search_at_begin: "Alan sonuna ulaşıldı. Baştan yeniden başla.",
move_popup: "Açılır arama penceresini taşı",
font_size: "--Yazı Tipi boyutu--",
go_to_line: "Satıra git(Ctrl+g)",
go_to_line_prompt: "Satır numarasına git:",
undo: "Geri al(Ctrl+z)",
redo: "Yeniden yap(Ctrl+y)",
change_smooth_selection: "bazı görüntü özellikleri etkin/etkisiz (daha akıllı görüntü ama daha fazla İşlemci yükü)",
highlight: "Sözdizimi vurgulama açık/kapalıya geç",
reset_highlight: "Vurgulamayı sıfırla (eğer metinde eşzamanlı değil)",
help: "Hakkında",
save: "Kaydet(Ctrl+s)",
load: "Yükle",
line_abbr: "St",
char_abbr: "Kr",
position: "Konum",
total: "Toplam",
close_popup: "Açılır pencereyi kapat",
shortcuts: "Kısayollar",
add_tab: "Metine tablolalama ekle",
remove_tab: "Metinden tablolamayı kaldır",
about_notice: "Bilgi: sözdizimi vurgulama işlevi sadece küçük metin içindir",
toggle: "Geçiş düzenelyici",
accesskey: "Erişim anahtarı",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Devam ediyor...",
fullscreen: "Tam ekran",
syntax_selection: "--Sözdizimi--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
syntax_robotstxt: "Robots txt",
syntax_tsql: "T-SQL",
syntax_perl: "Perl",
syntax_coldfusion: "Coldfusion",
close_tab: "Dosyayı kapat"
};
